spring.application.name=resqconnect

spring.datasource.url=jdbc:sqlserver://CRSVCSQLTRN02\\CORP_TRN;databaseName=training;integratedSecurity=true;encrypt=true;trustServerCertificate=true;

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
